name: PHP Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  auto-pull:
    name: main
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name muhammetsafak
          git config user.email info@muhammetsafak.com.tr
          git config github.token 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
          git pull origin main
        working-directory: ${{ secrets.REMOTE_PATH }}